# Generated by Django 5.2.8 on 2025-11-06 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('RESOLVIDO', 'Resolvido'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=15, verbose_name='Status')),
                ('category', models.CharField(choices=[('TI', 'Tecnologia da Informação'), ('PROCESSOS', 'Processos'), ('ATENDIMENTO', 'Atendimento'), ('OUTROS', 'Outros')], max_length=30, verbose_name='Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='anexos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incidentes.incidente')),
            ],
        ),
    ]
