# Generated by Django 5.2.8 on 2025-11-12 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='usuarios_que_editaram',
            field=models.ManyToManyField(blank=True, related_name='incidentes_editados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidente',
            name='usuarios_que_leram',
            field=models.ManyToManyField(blank=True, related_name='incidentes_lidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
