# Generated by Django 5.2.8 on 2025-11-12 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('TI', 'TI'), ('RH', 'RH'), ('Comercial', 'Comercial'), ('Atendimento', 'Atendimento'), ('Financeiro', 'Financeiro')], max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Separadas por vírgula (,)', max_length=200)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('versao', models.CharField(default='v1.0', max_length=10)),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
