# Generated by Django 5.2.8 on 2025-11-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('colab', 'Colaborador'), ('view', 'Visualizador')], default='view', max_length=20, verbose_name='Papel')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=20, verbose_name='Status')),
                ('last_login', models.CharField(blank=True, max_length=50, null=True, verbose_name='Último acesso')),
                ('incidents', models.IntegerField(default=0, verbose_name='Incidentes')),
                ('articles', models.IntegerField(default=0, verbose_name='Artigos')),
                ('can_view_incidents', models.BooleanField(default=True)),
                ('can_edit_incidents', models.BooleanField(default=False)),
                ('can_view_manuals', models.BooleanField(default=True)),
                ('can_edit_manuals', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
            ],
        ),
    ]
