# Generated by Django 5.2.8 on 2025-11-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('COLAB', 'Colaborador'), ('VIEW', 'Visualizador')], default='COLAB', max_length=50, verbose_name='Papel')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('SUSPENSO', 'Suspenso')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('last_login', models.CharField(blank=True, max_length=50, null=True, verbose_name='Último acesso')),
                ('incidents', models.IntegerField(default=0, verbose_name='Incidentes')),
                ('articles', models.IntegerField(default=0, verbose_name='Artigos')),
            ],
        ),
    ]
